#!python

#specify the sconscript for BufferTest
project = 'BufferTest'
SConscript('SConstruct' + project, exports=['project'])

#specify the sconscript for RecordTest
project = 'RecordTest'
SConscript('SConstruct' + project, exports=['project'])

#specify the sconscript for SortTest
project = 'SortTest'
SConscript('SConstruct' + project, exports=['project'])
