#!python



debugcflags = ['-W1', '-GX', '-EHsc', '-D_DEBUG', '/MDd']   #extra compile flags for debug
releasecflags = ['-O2', '-EHsc', '-DNDEBUG', '/MD']         #extra compile flags for release

env = Environment()

#make sure the sconscripts can get to the variables
Export('env', 'debugcflags', 'releasecflags')

#put all .sconsign files in one place
env.SConsignFile()

#specify the sconscript for myprogram
project = 'BufferTest'
SConscript('SConstruct' + project, exports=['project'])

#specify the sconscript for myprogram
project = 'RecordTest'
SConscript('SConstruct' + project, exports=['project'])
